//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_SOLUTION
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.EC_CLAIMS = new HashSet<EC_CLAIMS>();
        }
    
        public int ITEMID { get; set; }
        public Nullable<int> ASSID { get; set; }
        public string ITEM_NAME { get; set; }
    
        public virtual ASSESSEMENT ASSESSEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EC_CLAIMS> EC_CLAIMS { get; set; }
    }
}
